<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>_2LinkedListLooped</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageId>LinkedListLooped</PackageId>
    <Title>Double Looped Linked List</Title>
    <Version>1.0.0</Version>
    <Authors>Statist</Authors>
    <Description>A simple double linked list</Description>
    <Company>Statist</Company>
    <Product>LinkedListLooped</Product>
    <Copyright>no</Copyright>
  </PropertyGroup>

</Project>
